class Autogenerated {
  String id;

  Transaction transaction;

  Autogenerated({
    this.id,
    this.transaction,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];

    transaction = json['transaction'] != null
        ? new Transaction.fromJson(json['transaction'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;

    if (this.transaction != null) {
      data['transaction'] = this.transaction.toJson();
    }

    return data;
  }
}

class Transaction {
  String timezone;
  String created;
  String url;
  bool asynchronous;
  int amount;
  String currency;

  Transaction(
      {this.timezone,
      this.created,
      this.url,
      this.asynchronous,
      this.amount,
      this.currency});

  Transaction.fromJson(Map<String, dynamic> json) {
    timezone = json['timezone'];
    created = json['created'];
    url = json['url'];

    asynchronous = json['asynchronous'];
    amount = json['amount'];
    currency = json['currency'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['timezone'] = this.timezone;
    data['created'] = this.created;
    data['url'] = this.url;
    data['asynchronous'] = this.asynchronous;
    data['amount'] = this.amount;
    data['currency'] = this.currency;
    return data;
  }
}
