// class Autogenerated {
//   0 00;
//   0 01;
//   0 02;
//   0 04;
//   0 05;
//   6 66;
//   0 07;
//   0 08;
//   0 09;
//
//   Autogenerated({this.00, this.01, this.02, this.04, this.05, this.66, this.07, this.08, this.09});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//   00 = json['0'] != null ? new 0.fromJson(json['0']) : null;
//   01 = json['1'] != null ? new 0.fromJson(json['1']) : null;
//   02 = json['2'] != null ? new 0.fromJson(json['2']) : null;
//   04 = json['4'] != null ? new 0.fromJson(json['4']) : null;
//   05 = json['5'] != null ? new 0.fromJson(json['5']) : null;
//   66 = json['6'] != null ? new 6.fromJson(json['6']) : null;
//   07 = json['7'] != null ? new 0.fromJson(json['7']) : null;
//   08 = json['8'] != null ? new 0.fromJson(json['8']) : null;
//   09 = json['9'] != null ? new 0.fromJson(json['9']) : null;
//   }
//
//   Map<String, dynamic> toJson() {
//   final Map<String, dynamic> data = new Map<String, dynamic>();
//   if (this.00 != null) {
//   data['0'] = this.00.toJson();
//   }
//   if (this.01 != null) {
//   data['1'] = this.01.toJson();
//   }
//   if (this.02 != null) {
//   data['2'] = this.02.toJson();
//   }
//   if (this.04 != null) {
//   data['4'] = this.04.toJson();
//   }
//   if (this.05 != null) {
//   data['5'] = this.05.toJson();
//   }
//   if (this.66 != null) {
//   data['6'] = this.66.toJson();
//   }
//   if (this.07 != null) {
//   data['7'] = this.07.toJson();
//   }
//   if (this.08 != null) {
//   data['8'] = this.08.toJson();
//   }
//   if (this.09 != null) {
//   data['9'] = this.09.toJson();
//   }
//   return data;
//   }
// }
//
// class 0 {
// String environment;
// String name;
// String publicKey;
// int active;
// String paymentMethod;
// String paymentCurrency;
//
// 0({this.environment, this.name, this.publicKey, this.active, this.paymentMethod, this.paymentCurrency});
//
// 0.fromJson(Map<String, dynamic> json) {
// environment = json['environment'];
// name = json['name'];
// publicKey = json['public_key'];
// active = json['active'];
// paymentMethod = json['payment_method'];
// paymentCurrency = json['payment_currency'];
// }
//
// Map<String, dynamic> toJson() {
// final Map<String, dynamic> data = new Map<String, dynamic>();
// data['environment'] = this.environment;
// data['name'] = this.name;
// data['public_key'] = this.publicKey;
// data['active'] = this.active;
// data['payment_method'] = this.paymentMethod;
// data['payment_currency'] = this.paymentCurrency;
// return data;
// }
// }
//
// class 6 {
// String environment;
// String publicKey;
// String name;
// String rAZORPAYKEY;
// String rAZORPAYSECRET;
// int active;
// String paymentCurrency;
// String paymentMethod;
//
// 6({this.environment, this.publicKey, this.name, this.rAZORPAYKEY, this.rAZORPAYSECRET, this.active, this.paymentCurrency, this.paymentMethod});
//
// 6.fromJson(Map<String, dynamic> json) {
// environment = json['environment'];
// publicKey = json['public_key'];
// name = json['name'];
// rAZORPAYKEY = json['RAZORPAY_KEY'];
// rAZORPAYSECRET = json['RAZORPAY_SECRET'];
// active = json['active'];
// paymentCurrency = json['payment_currency'];
// paymentMethod = json['payment_method'];
// }
//
// Map<String, dynamic> toJson() {
// final Map<String, dynamic> data = new Map<String, dynamic>();
// data['environment'] = this.environment;
// data['public_key'] = this.publicKey;
// data['name'] = this.name;
// data['RAZORPAY_KEY'] = this.rAZORPAYKEY;
// data['RAZORPAY_SECRET'] = this.rAZORPAYSECRET;
// data['active'] = this.active;
// data['payment_currency'] = this.paymentCurrency;
// data['payment_method'] = this.paymentMethod;
// return data;
// }
// }
//
// class Autogenerated {
// 0 00;
// 0 01;
// 0 02;
// 0 04;
// 0 05;
// 6 66;
// 0 07;
// 0 08;
// 0 09;
//
// Autogenerated({this.00, this.01, this.02, this.04, this.05, this.66, this.07, this.08, this.09});
//
// Autogenerated.fromJson(Map<String, dynamic> json) {
// 00 = json['0'] != null ? new 0.fromJson(json['0']) : null;
// 01 = json['1'] != null ? new 0.fromJson(json['1']) : null;
// 02 = json['2'] != null ? new 0.fromJson(json['2']) : null;
// 04 = json['4'] != null ? new 0.fromJson(json['4']) : null;
// 05 = json['5'] != null ? new 0.fromJson(json['5']) : null;
// 66 = json['6'] != null ? new 6.fromJson(json['6']) : null;
// 07 = json['7'] != null ? new 0.fromJson(json['7']) : null;
// 08 = json['8'] != null ? new 0.fromJson(json['8']) : null;
// 09 = json['9'] != null ? new 0.fromJson(json['9']) : null;
// }
//
// Map<String, dynamic> toJson() {
// final Map<String, dynamic> data = new Map<String, dynamic>();
// if (this.00 != null) {
// data['0'] = this.00.toJson();
// }
// if (this.01 != null) {
// data['1'] = this.01.toJson();
// }
// if (this.02 != null) {
// data['2'] = this.02.toJson();
// }
// if (this.04 != null) {
// data['4'] = this.04.toJson();
// }
// if (this.05 != null) {
// data['5'] = this.05.toJson();
// }
// if (this.66 != null) {
// data['6'] = this.66.toJson();
// }
// if (this.07 != null) {
// data['7'] = this.07.toJson();
// }
// if (this.08 != null) {
// data['8'] = this.08.toJson();
// }
// if (this.09 != null) {
// data['9'] = this.09.toJson();
// }
// return data;
// }
// }
